disabled_rules:
  - nesting
included:
  - LicensesViewController
analyzer_rules:
  - explicit_self
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length: 150
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
reporter: "xcode"
